-- SYSTEM_ADMIN: full permissions
INSERT INTO dbo.role_permission (role_id, permission_id)
SELECT 'SYSTEM_ADMIN', name FROM dbo.Permission;

-- WORKSPACE_ADMIN
INSERT INTO dbo.role_permission (role_id, permission_id) VALUES
('WORKSPACE_ADMIN', 'WORKSPACE_VIEW'),
('WORKSPACE_ADMIN', 'WORKSPACE_UPDATE'),
('WORKSPACE_ADMIN', 'WORKSPACE_DELETE'),
('WORKSPACE_ADMIN', 'WORKSPACE_ADD_MEMBER'),
('WORKSPACE_ADMIN', 'WORKSPACE_EDIT_MEMBER'),
('WORKSPACE_ADMIN', 'WORKSPACE_INVITE_MEMBER'),
('WORKSPACE_ADMIN', 'WORKSPACE_REMOVE_MEMBER'),
('WORKSPACE_ADMIN', 'WORKSPACE_LIST_MEMBER'),
('WORKSPACE_ADMIN', 'CYCLE_CREATE'),
('WORKSPACE_ADMIN', 'CYCLE_EDIT'),
('WORKSPACE_ADMIN', 'CYCLE_DELETE'),
('WORKSPACE_ADMIN', 'CYCLE_VIEW'),
('WORKSPACE_ADMIN', 'JOB_POSITION_CREATE'),
('WORKSPACE_ADMIN', 'JOB_POSITION_EDIT'),
('WORKSPACE_ADMIN', 'JOB_POSITION_DELETE'),
('WORKSPACE_ADMIN', 'JOB_POSITION_VIEW'),
('WORKSPACE_ADMIN', 'MEASURE_UNITS_ADD'),
('WORKSPACE_ADMIN', 'MEASURE_UNITS_EDIT'),
('WORKSPACE_ADMIN', 'MEASURE_UNITS_DELETE'),
('WORKSPACE_ADMIN', 'MEASURE_UNITS_VIEW'),
('WORKSPACE_ADMIN', 'TEAM_CREATE'),
('WORKSPACE_ADMIN', 'TEAM_EDIT'),
('WORKSPACE_ADMIN', 'TEAM_DELETE'),
('WORKSPACE_ADMIN', 'TEAM_VIEW_DETAIL'),
('WORKSPACE_ADMIN', 'WP_OKR_CREATE'),
('WORKSPACE_ADMIN', 'WP_OKR_EDIT'),
('WORKSPACE_ADMIN', 'WP_OKR_DELETE'),
('WORKSPACE_ADMIN', 'WP_OKR_VIEW_DETAIL'),
('WORKSPACE_ADMIN', 'WP_OKR_APPROVE_CHECKIN'),
('WORKSPACE_ADMIN', 'WP_OKR_CLOSE'),
('WORKSPACE_ADMIN', 'PERSONAL_OKR_CREATE'),
('WORKSPACE_ADMIN', 'PERSONAL_OKR_EDIT'),
('WORKSPACE_ADMIN', 'PERSONAL_OKR_DELETE'),
('WORKSPACE_ADMIN', 'PERSONAL_OKR_VIEW');

-- TEAM_LEADER
INSERT INTO dbo.role_permission (role_id, permission_id) VALUES
('TEAM_LEADER', 'WORKSPACE_VIEW'),
('TEAM_LEADER', 'WORKSPACE_LIST_MEMBER'),
('TEAM_LEADER', 'TEAM_VIEW_DETAIL'),
('TEAM_LEADER', 'TEAM_OKR_CREATE'),
('TEAM_LEADER', 'TEAM_OKR_EDIT'),
('TEAM_LEADER', 'TEAM_OKR_DELETE'),
('TEAM_LEADER', 'TEAM_OKR_VIEW_DETAIL'),
('TEAM_LEADER', 'TEAM_OKR_APPROVE_CHECKIN'),
('TEAM_LEADER', 'TEAM_OKR_CLOSE'),
('TEAM_LEADER', 'WP_OKR_SUBMIT_CHECKIN'),
('TEAM_LEADER', 'WP_OKR_REQUEST_CHECKIN'),
('TEAM_LEADER', 'WP_OKR_VIEW_DETAIL'),
('TEAM_LEADER', 'PERSONAL_OKR_CREATE'),
('TEAM_LEADER', 'PERSONAL_OKR_EDIT'),
('TEAM_LEADER', 'PERSONAL_OKR_DELETE'),
('TEAM_LEADER', 'PERSONAL_OKR_VIEW');

-- TEAM_MEMBER
INSERT INTO dbo.role_permission (role_id, permission_id) VALUES
('TEAM_MEMBER', 'WORKSPACE_VIEW'),
('TEAM_MEMBER', 'WORKSPACE_LIST_MEMBER'),
('TEAM_MEMBER', 'TEAM_VIEW_DETAIL'),
('TEAM_MEMBER', 'TEAM_OKR_VIEW_DETAIL'),
('TEAM_MEMBER', 'TEAM_OKR_SUBMIT_CHECKIN'),
('TEAM_MEMBER', 'TEAM_OKR_REQUEST_CHECKIN'),
('TEAM_MEMBER', 'PERSONAL_OKR_CREATE'),
('TEAM_MEMBER', 'PERSONAL_OKR_EDIT'),
('TEAM_MEMBER', 'PERSONAL_OKR_DELETE'),
('TEAM_MEMBER', 'PERSONAL_OKR_VIEW');

-- WORKSPACE_MEMBER
INSERT INTO dbo.role_permission (role_id, permission_id) VALUES
('WORKSPACE_MEMBER', 'WORKSPACE_VIEW'),
('WORKSPACE_MEMBER', 'WORKSPACE_LIST_MEMBER'),
('WORKSPACE_MEMBER', 'WP_OKR_VIEW_DETAIL'),
('WORKSPACE_MEMBER', 'PERSONAL_OKR_CREATE'),
('WORKSPACE_MEMBER', 'PERSONAL_OKR_EDIT'),
('WORKSPACE_MEMBER', 'PERSONAL_OKR_DELETE'),
('WORKSPACE_MEMBER', 'PERSONAL_OKR_VIEW');
