INSERT INTO dbo.[role_permission] (role_id, permission_id)
SELECT 'SUPER_ADMIN', p.name
FROM dbo.permission p;
GO


INSERT INTO dbo.[role_permission] (role_id, permission_id) VALUES
('WORKSPACE_ADMIN', 'WORKSPACE_VIEW'),
('WORKSPACE_ADMIN', 'WORKSPACE_UPDATE'),
('WORKSPACE_ADMIN', 'WORKSPACE_INVITE_MEMBER'),
('WORKSPACE_ADMIN', 'WORKSPACE_REMOVE_MEMBER'),
('WORKSPACE_ADMIN', 'WORKSPACE_MANAGE_ROLES'),

('WORKSPACE_ADMIN', 'OBJECTIVE_CREATE'),
('WORKSPACE_ADMIN', 'OBJECTIVE_UPDATE'),
('WORKSPACE_ADMIN', 'OBJECTIVE_DELETE'),
('WORKSPACE_ADMIN', 'OBJECTIVE_VIEW'),

('WORKSPACE_ADMIN', 'KR_CREATE'),
('WORKSPACE_ADMIN', 'KR_UPDATE'),
('WORKSPACE_ADMIN', 'KR_DELETE'),
('WORKSPACE_ADMIN', 'KR_VIEW'),

('WORKSPACE_ADMIN', 'CHECKIN_CREATE'),
('WORKSPACE_ADMIN', 'CHECKIN_UPDATE'),
('WORKSPACE_ADMIN', 'CHECKIN_VIEW');
GO


INSERT INTO dbo.[role_permission] (role_id, permission_id) VALUES
('WORKSPACE_MEMBER', 'OBJECTIVE_VIEW'),
('WORKSPACE_MEMBER', 'KR_VIEW'),
('WORKSPACE_MEMBER', 'CHECKIN_CREATE'),
('WORKSPACE_MEMBER', 'CHECKIN_VIEW'),
('WORKSPACE_MEMBER', 'CHECKIN_UPDATE');
GO